"PR: Docs":
- changed-files:
  - any-glob-to-any-file: ['docs/*', 'guides/*', '**/*.md']

"PR: CI":
- changed-files:
  - any-glob-to-any-file: ['.github/*', '**/*.yml', '.gitattributes', '.gitignore']

"PR: JSON":
- changed-files:
  - all-globs-to-any-file: ['**/*.json']

"PR: Audio":
- changed-files:
  - any-glob-to-any-file: ['**/snd_*', '**/*.ogg', '**/*.wav']

"PR: Sprites":
- changed-files:
  - any-glob-to-any-file: ['**/*.png', '**/spr_*']
  
