name: Release-Windows-YYC
on: 
  push:
    tags:        
      - v*.*.*
jobs:
  gamemaker_build:
    name: Build
    uses: ./.github/workflows/gamemaker_build.yml
    secrets: inherit
    with:
      development: false
      yyc: true
  release:
    name: Release
    runs-on: windows-2022
    needs: gamemaker_build
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Download built file artifact
        uses: actions/download-artifact@v3
        with:
          name: built-file
          path: ./build_output
      - id: create_release
        name: Create Release
        uses: softprops/action-gh-release@v2.0.9
        with:
          name: ChapterMaster ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: |
            ./build_output/${{ needs.gamemaker_build.outputs.built_file }}/*
